# Generated by Django 4.1 on 2023-10-11 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_department"),
    ]

    operations = [
        migrations.RenameField(
            model_name="department", old_name="name", new_name="title",
        ),
    ]
