# Generated by Django 4.1 on 2023-10-16 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0003_rename_name_department_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfor", name="age", field=models.IntegerField(default=99),
        ),
    ]
