# Generated by Django 4.1 on 2023-12-10 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app02", "0003_city"),
    ]

    operations = [
        migrations.CreateModel(
            name="Admin1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=32, verbose_name="用户名")),
                ("password", models.CharField(max_length=64, verbose_name="密码")),
                ("img", models.CharField(max_length=128, verbose_name="图片")),
            ],
        ),
        migrations.AlterField(
            model_name="city",
            name="count",
            field=models.IntegerField(max_length=64, verbose_name="人口"),
        ),
        migrations.AlterField(
            model_name="city",
            name="img",
            field=models.FileField(
                max_length=128, upload_to="city/", verbose_name="LOGO"
            ),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="age",
            field=models.IntegerField(verbose_name="年龄"),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="enroll",
            field=models.DateField(verbose_name="入职时间"),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="name",
            field=models.CharField(max_length=16, verbose_name="姓名"),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="password",
            field=models.CharField(max_length=64, verbose_name="密码"),
        ),
    ]
