# Generated by Django 4.1 on 2023-11-26 05:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app02", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=32, verbose_name="用户名")),
                ("password", models.CharField(max_length=64, verbose_name="密码")),
            ],
        ),
        migrations.CreateModel(
            name="PhoneNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=11, verbose_name="手机号")),
                ("price", models.IntegerField(verbose_name="价格")),
                (
                    "level",
                    models.SmallIntegerField(
                        choices=[(1, "一级"), (2, "二级"), (3, "三级"), (4, "四级")],
                        default=1,
                        verbose_name="级别",
                    ),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(1, "已占用"), (2, "未占用")], default=2, verbose_name="状态"
                    ),
                ),
            ],
        ),
        migrations.RemoveField(model_name="userinfo", name="create_time",),
        migrations.AddField(
            model_name="userinfo",
            name="enroll",
            field=models.DateField(default=datetime.date.today, verbose_name="入职时间"),
        ),
        migrations.AlterField(
            model_name="department",
            name="title",
            field=models.CharField(max_length=32, verbose_name="标题"),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="age",
            field=models.IntegerField(default=18, verbose_name="年龄"),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="depart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="app02.department",
                verbose_name="部门名称",
            ),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="name",
            field=models.CharField(
                default="zhangsan", max_length=16, verbose_name="姓名"
            ),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="password",
            field=models.CharField(default="123", max_length=64, verbose_name="密码"),
        ),
    ]
